### ISSUE TITLE
on behalf of Neal and Meredith

### ISSUE THREAD

**Issue by jonasalmeida** [episphere/mortalitytracker#4]
[7:08 AM] Freedman, Neal (NIH/NCI) [E]
So I wonder if we could add a panel that has covid deaths from hopkins plotted along side covid+p+i, as they call it, from NCHS.
Edited
[7:09 AM] Shiels, Meredith (NIH/NCI) [E]
I agree it would be great to have the COVID deaths and the COVID+flu+pneumonia has an option

**Comment by freedmanne** [comment]
hi Jonas, I am in! do you know are the covid mortality data from Hopkins the ones that everyone is using? or are there other competing high quality sources for USA

**Comment by jonasalmeida** [comment]
fresh start
