### ISSUE TITLE
Neal's collated together COVID tracker requests

### ISSUE THREAD

**Issue by freedmanne** [episphere/mortalitytracker#6]
hi Jonas, I have put them together. 
1) Could you reduce the thickness of the historical average line. so it is half or a third as thick as the 2020 data. 
2) Additionally, I'd like to revisit creating a dashboard where you can load it up and it will simultaneously display the whole country and specific states. I think this will be very useful for our own knowledge and thinking about reopening. I had mentioned 12 separate panels if possible, including for overall mortality and then top 8 states with high covid deaths, and then DC, MD, and VA. Amy, mentioned a similar dashboard where it could show the most rapidly changing states.

**Comment by jonasalmeida** [comment]
> Could you reduce the thickness of the historical average line. so it is half or a third as thick as the 2020 data.

done

**Comment by jonasalmeida** [comment]
> Additionally, I'd like to revisit creating a dashboard where you can load it up and it will simultaneously display the whole country and specific states. I think this will be very useful for our own knowledge and thinking about reopening. I had mentioned 12 separate panels if possible, including for overall mortality and then top 8 states with high covid deaths, and then DC, MD, and VA. Amy, mentioned a similar dashboard where it could show the most rapidly changing states.

Understood - that is the next step indeed - a dashboard where you can choose the sates or the whole country and have as many as you want. I'll start that one after adding case count to the old [USTable](https://episphere.github.io/corona/UStable).
