### ISSUE TITLE
Adding FAQ

### ISSUE THREAD

**Issue by freedmanne** [episphere/mortalitytracker#9]
Hi, could we add FAQ section to the site-- I am attaching final version that Stephen approved. 
thanks,
Neal
[FAQ for website.5.11.2020.docx](https://github.com/episphere/mortalitytracker/files/4622384/FAQ.for.website.5.11.2020.docx)

**Comment by jonasalmeida** [comment]
Thank you Neal, done

**Comment by freedmanne** [comment]
looks great, thanks!
